# Generated by Django 5.2.14 on 2026-05-21 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restauran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RestauranTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RestauranPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoName', models.CharField(max_length=50)),
                ('restauran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restauran')),
            ],
        ),
        migrations.AddField(
            model_name='restauran',
            name='restauranType',
            field=models.ManyToManyField(to='myapp.restaurantypes'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('isVisible', models.BooleanField(default=True)),
                ('restauran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restauran')),
            ],
        ),
    ]
